### PR TITLE
Add Proj.bounds function

### PR DESCRIPTION
**Pull request by simonbyrne**
Now we've upgraded the library, we can expose this interface.

See discussion in https://github.com/MakieOrg/GeoMakie.jl/pull/101

### CODE REVIEW

**Comment by rafaqz** [comment]
There is also https://github.com/rafaqz/Extents.jl that we use in GeoInterface.jl and DimensionslData.jl/Rasters.jl for this.

It's basically bounds with a type wrapper and explicit dimension name and order

**Comment by simonbyrne** [comment]
@rafaqz I'm not quite sure I understand: are you suggesting we import Extent into Proj, or import Proj into Extent?

**Comment by rafaqz** [comment]
import Extent

It's a tiny package just to have a shared wrapper for extents/bounding boxes.

Maybe I misunderstand what your `bounds` method is here

**Review by visr — APPROVED** [review]
This looks good to me, thanks for adding it!

**Comment by visr** [comment]
@rafaqz it probably makes sense to also support Extents, but that can be done in a separate PR, right? Perhaps by adding a method to Proj.bounds that returns an Extent when that is the input? Or would this definition be in the way?

**Comment by simonbyrne** [comment]
Probably best to do that as another PR?

I've opened https://github.com/MakieOrg/GeoMakie.jl/pull/132, which uses this.

**Comment by rafaqz** [comment]
Yeah it can totally be in another PR, I was just pointing out we mostly are using `Extent` for passing around this information now in JuliaGeo.

**Comment by simonbyrne** [comment]
can we merge this and tag a new release?

**Pull request merged**
